# Generated by Django 2.0.5 on 2018-09-04 13:02

from django.db import migrations
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contact_phone_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='picture',
            field=s3direct.fields.S3DirectField(),
        ),
        migrations.AlterField(
            model_name='audio',
            name='file',
            field=s3direct.fields.S3DirectField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='poster',
            field=s3direct.fields.S3DirectField(),
        ),
        migrations.AlterField(
            model_name='mixtape',
            name='poster',
            field=s3direct.fields.S3DirectField(),
        ),
        migrations.AlterField(
            model_name='mypics',
            name='file',
            field=s3direct.fields.S3DirectField(),
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=s3direct.fields.S3DirectField(),
        ),
    ]
